// lang.js · every word the Hub shows, in English and Spanish.
// The code never contains a sentence; it asks for one by key.
window.LANG = {
  en: {
    appName: 'Colorado Referees',
    signinTitle: 'Sign in',
    signinLead: 'Use the email address on your referee record.',
    email: 'Your email address',
    sendCode: 'Email me a code',
    sending: 'Sending your code...',
    codeSent: 'Check your email for a 6-digit code. It is good for 10 minutes.',
    codeLabel: 'The code we emailed you',
    signIn: 'Sign in',
    noRecord: 'We could not find a referee record with that email. Use the address on your Learning Center account, or ask at Referee HQ.',
    tooMany: 'Too many codes sent just now. Wait a few minutes and try again.',
    couldNotSend: 'Could not send a code: ',
    badCode: 'That code did not work. Check the digits and try again.',
    wholeCode: 'Type the whole code from the email.',
    greeting: { morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening' },
    minutesToKickoff: 'minutes<br>to kickoff',
    hoursToKickoff: 'hours<br>to kickoff',
    kickedOff: 'kicked off',
    minAgo: 'minutes ago',
    noGamesToday: 'No games on your record today.',
    noGamesHint: 'When Assignr publishes your next game it shows here. Until then, the Library is a good place to be.',
    nextGame: 'Your next game',
    youAre: 'You are the',
    role: { cr: 'referee', ar1: 'assistant referee 1', ar2: 'assistant referee 2', fourth: 'fourth official' },
    checkIn: 'CHECK IN',
    checkingIn: 'Checking in...',
    checkedIn: 'CHECKED IN',
    checkedInAt: 'Staff can see you are here.',
    checkinFailed: 'Could not check in. Your tap is saved; tap again when you have signal, or check in at Referee HQ.',
    checkinWhere: 'Check in at Referee HQ when you arrive.',
    details: 'Details',
    laterToday: 'Later today',
    noteFrom: 'after',
    allNotes: 'All your notes',
    noNotes: 'No feedback yet. When a coach or mentor watches one of your games, their note lands here.',
    fromState: 'From Colorado Soccer',
    rules: 'Rules',
    map: 'Map',
    help: 'I NEED HELP',
    yourDay: 'Your day',
    back: 'Back',
    kicksIn: 'Kicks off in',
    home: 'Home, in dark',
    away: 'Away, in light',
    crew: 'Your crew',
    alone: 'This is your game alone; no assistants at this format.',
    afterGame: 'AFTER THE GAME',
    reportScore: 'Report the score',
    reportScoreHint: 'Then hand the game card to HQ. Scores also go in PlayMetrics, as always.',
    incident: 'File an incident report',
    incidentHint: 'A written report, in your words, for a send-off, dismissal or anything unusual',
    incidentNote: 'A report is read by the referee department; it does not page anyone. If something is happening right now, use I NEED HELP. Cautions and send-offs also go in your Assignr game report, as always.',
    comingSoon: 'Coming soon here. For now, use the current page.',
    helpTitle: "WHAT'S GOING ON?",
    helpLead: 'Pick one. It goes to Referee HQ with your name and field. Nothing sends until you confirm.',
    reasons: {
      roster: 'Roster or game card problem',
      spectator: 'Coach or spectator problem',
      redcard: 'Red card or send-off',
      fight: 'Fight or threat',
      injury: 'Injury, I need the trainer'
    },
    hotline: 'Text the Referee Hotline',
    groupUrgent: 'Texts the Site Coordinator and staff at your site right now',
    groupQueue: 'A message to Referee HQ',
    groupHotline: 'No staff where you are, or something else',
    hotlineDesktop: 'Text the Referee Hotline from your phone:',
    hotlineNote: 'A Referee Coach watches the hotline all day, every day. Use it when there is no Site Coordinator where you are, or for anything not on this list.',
    youPicked: 'You picked',
    goesTo: 'Texts the Site Coordinator and everyone who can respond at your site right now.',
    goesToQueue: 'Goes to Referee HQ as a message.',
    sendIt: 'SEND IT',
    neverMind: 'Never mind',
    sendingHelp: 'Sending...',
    helpSent: 'Sent. Referee HQ has it.',
    helpSentAt: 'Sent at',
    helpFailed: 'Could not send. Text the hotline instead:',
    helpFoot: 'If the site has no staff signed in, everything here goes to the hotline instead.',
    coachingEntry: 'Coaching',
    coachingEntryHint: 'Watch a game and leave a note',
    coachingTitle: 'COACHING',
    coachingLead: 'Pick where you are. Every game there is listed; tap one to write a note on a referee.',
    noVenuesToday: 'No games anywhere today.',
    venue: 'Venue',
    myNotes: 'My notes',
    myNotesLead: 'What you wrote, and what it became after cleanup. You always see both.',
    noMyNotes: 'You have not written a note yet.',
    crewPick: 'Who did you watch?',
    noteLabel: 'Your note',
    notePlaceholder: 'What you saw, what was good, one thing to work on. Write it like you would say it.',
    areaLabel: 'Which area does this speak to? (optional)',
    areas: { laws: 'Laws', reading: 'Reading the game', fitness: 'Fitness', presence: 'How you carry yourself' },
    saveNote: 'SAVE NOTE',
    savingNote: 'Saving...',
    noteSaved: 'Saved and signed',
    noteSavedHint: 'It goes to cleanup next, then to the Director of Referee Development. You can see it any time under My notes.',
    noteFailed: 'Could not save. Your words are still here; tap again when you have signal.',
    another: 'Note another referee on this game',
    rawLabel: 'What you wrote',
    cleanLabel: 'After cleanup',
    notCleaned: 'Not cleaned yet',
    status: { pending: 'Waiting for cleanup', cleaned: 'Cleaned, waiting for approval', approved: 'Approved, sent to the referee', edited: 'Approved, sent to the referee', rejected: 'Not sent' },
    signedAs: 'Signed as',
    reviewEntry: 'Feedback review',
    reviewEntryHint: 'Clean, approve and release feedback to referees',
    reviewTitle: 'REVIEW',
    reviewLead: 'Every note a coach wrote: what they wrote, what cleanup made of it, what the referee will get. Clean what is waiting, read it, approve to release. A released note reaches the referee in their Hub at once, and the coach sees all three versions.',
    filterPending: 'Waiting',
    filterCleaned: 'Cleaned',
    filterApproved: 'Approved',
    loadingReview: 'Loading notes...',
    nothingHere: 'Nothing here.',
    cleanBtn: 'Clean this note',
    cleanAll: 'Clean all waiting',
    cleaning: 'Cleaning...',
    approveBtn: 'APPROVE AND RELEASE',
    approveAll: 'Approve and release all cleaned',
    approving: 'Approving...',
    approved: 'Approved',
    approvedBy: 'by',
    flaggedNote: 'Flagged by cleanup: read before approving',
    reviewFailed: 'That did not go through. Try again.',
    notAllowed: 'Your titles do not open Review.',
    count: { one: '1 note', many: '{n} notes' },
    notSeen: 'Not seen yet',
    notSeenLong: 'Nobody has left this referee a note yet. Yours would be the first.',
    seenTimes: 'Seen {n} times, last',
    alreadySaid: 'Already said about this referee ({n} released notes). Add to it, do not repeat it.',
    redMeans: 'A name in red has had no feedback yet. Those are the ones to see first.',
    aiLabel: 'After cleanup',
    releasedLabel: 'Sent to the referee',
    notReleased: 'Not released yet',
    readBy: 'Read by the referee on',
    centerEntry: 'Referee development',
    centerEntryHint: 'Coverage, coaches, scheduling, and the AI coach for coaches',
    centerTitle: 'REFEREE DEVELOPMENT',
    centerLead: 'Who has been seen, who has not, what the coaches are doing, and help for the coaches themselves.',
    tabCoverage: 'Coverage',
    tabCoaches: 'Coaches',
    tabAi: 'AI coach',
    tabQueue: 'Queue',
    stWorked: 'referees working this season',
    stSeen: 'seen at least once',
    stNever: 'never seen',
    stRead: 'released notes read',
    neverSeenTitle: 'Never seen, most games first',
    seenOnce: 'Seen once',
    gamesWorked: 'games',
    lastGame: 'last game',
    coachesTitle: 'Coaches and mentors, last 30 days',
    coachNotes: 'notes',
    coachRefs: 'referees',
    coachReleased: 'released',
    coachRead: 'read',
    noCoachActivity: 'No notes in the last 30 days.',
    aiLead: 'Reads every note a coach wrote in a date range and drafts a short, kind message to each coach: what landed well, what to tighten, how to give the referee more in fewer words. Nothing sends until you tap Send.',
    aiFrom: 'From',
    aiTo: 'To',
    aiRun: 'DRAFT COACHING NOTES',
    aiRunning: 'Reading the notes and drafting...',
    aiNone: 'No notes in that range.',
    aiSend: 'Send to',
    aiSending: 'Sending...',
    aiSent: 'Sent',
    aiNoEmail: 'No email on file for this coach',
    aiFailed: 'That did not go through.',
    queueWaiting: 'waiting for cleanup',
    queueCleaned: 'cleaned, ready to release',
    openReview: 'Open Review',
    opsEntry: 'Command Center',
    opsEntryHint: 'Every venue, crew and check-in, live. Switches, Help, Protection, bulletins',
    opsTitle: 'COMMAND CENTER',
    opsLead: 'Every venue with games on the day. Green is checked in. Red is a Help call still open.',
    tabBoard: 'Venues',
    tabRetain: 'Retain',
    tabBulletins: 'Bulletins',
    stVenues: 'venues',
    stGames: 'games',
    stCheckedIn: 'checked in',
    stHelpOpen: 'help open',
    noGamesDay: 'No games on this day.',
    allVenues: 'All venues',
    helpOpenAt: 'Help open',
    ackInOld: 'Acknowledge Help calls in the current Command Center for now.',
    retainLead: 'Referees who are working but nobody has seen, and referees who have gone quiet.',
    retainNever: 'Working, never seen (3+ games)',
    retainQuiet: 'No game in 30 days',
    noneHere: 'Nobody here. Good.',
    bulletinsLead: 'What every referee sees on Your day. Live ones are in their date window.',
    bulletinLive: 'Live',
    bulletinOver: 'Over',
    bulletinFuture: 'Scheduled',
    newBulletin: 'New bulletin',
    bulTitle: 'Title',
    bulBody: 'Message',
    bulFrom: 'From',
    bulTo: 'To',
    bulPost: 'POST',
    bulPosting: 'Posting...',
    bulPosted: 'Posted. Referees see it now.',
    bulClear: 'Take down',
    bulCleared: 'Taken down',
    ackEnroute: 'On my way',
    ackHandled: 'Handled',
    change: 'Change',
    fieldLabel: 'Field',
    saveChanges: 'SAVE CHANGES',
    saving: 'Saving...',
    peopleEntry: 'People',
    peopleEntryHint: 'Find anyone, give or remove a Colorado title',
    peopleTitle: 'PEOPLE',
    peopleLead: 'Type a name. Titles from the Learning Center come in on their own and cannot be changed here. Colorado titles are yours to give.',
    peopleSearch: 'Search by name',
    noMatch: 'No one by that name.',
    lcTitles: 'From the Learning Center',
    coTitles: 'Colorado titles',
    addTitle: 'Add a title',
    remove: 'Remove',
    greenBadge: 'Green badge (under 18)',
    titleGiven: 'Added',
    titleTaken: 'Removed',
    noneYet: 'None yet',
    tabProtection: 'Protection',
    protectionLead: 'Assignments in the next two weeks where the age group is above the referee\'s age. A heads-up for you and the assignor. Not a mark against the referee.',
    alertRefresh: 'Check assignments now',
    alertsOpen: 'Open',
    alertsHandled: 'Handled',
    alertAgeMsg: '{group} is above this referee\'s age ({age}).',
    adult: 'Adult',
    alertSeenBtn: 'Seen, assignor told',
    alertDismissBtn: 'Fine as is',
    alertSeen: 'Seen',
    alertDismissed: 'Fine as is',
    alertOnGame: 'Age-group warning on {n} of this crew',
    tabSchedule: 'Schedule',
    scheduleLead: 'Pick the day and the block, then a venue, then the fields, then the coach. A block means: debrief every referee on those fields, face to face, then walk the venue.',
    blockAm: 'Morning',
    blockPm: 'Afternoon',
    blockAll: 'All day',
    availableCount: '{n} coaches said they are free for this block.',
    availableMeans: 'A check mark means the coach said they are free for this block. You can still pick anyone.',
    pickFields: 'Fields (none picked means the whole venue)',
    wholeVenue: 'the whole venue',
    addCoach: 'Add a coach or mentor',
    coachSearch: 'Type a name',
    yourBlock: 'Your block today',
    blockJob: 'Debrief every referee on these fields face to face, then walk the venue and note anyone.',
    debriefed: 'Noted so far: {d} of {n} referees on your fields.',
    whenFree: 'When are you free to coach? Tap what you can do.',
    yours: 'yours',
    goldMeans: 'Gold-edged games are on your fields in your block.',
    coachHereToday: 'A coach or mentor is at your venue today. Say hello.',
    lanyard: 'Look for the CSA lanyard and name tag.',
    badgeCaption: 'Black badge on a lanyard, with the coach\'s name and title.',
    scoreSent: 'Score sent',
    scoreFix: 'Wrong? Change it below.',
    scoreChange: 'Change the score',
    scoreLater: 'Report the score here after the final whistle.',
    scoreSend: 'SEND THE SCORE',
    sending: 'Sending...',
    scoreBoth: 'Both scores, please.',
    scoreFailed: 'Could not send the score. Try again, or tell HQ.',
    previewing: 'Viewing as {name}.',
    previewNoWrite: 'Looking only; nothing you tap is sent.',
    previewStop: 'Stop viewing as',
    viewAs: 'View as (ADMIN)',
    viewAsHint: 'See the app exactly as another person sees it. Nothing you do while viewing is saved.',
    setupEntry: 'Setup',
    setupEntryHint: 'Events and tools, without touching the sheet',
    setupTitle: 'EVENTS',
    setupLead: 'A tournament or a league, what it switches on, and where its games are. Nothing saves until it is complete.',
    newEvent: 'New event',
    evName: 'Name',
    evId: 'Short id (letters and dashes; it becomes the address)',
    evType: 'Type',
    evTournament: 'Tournament',
    evLeague: 'League',
    evDates: 'Dates',
    evVenues: 'Venues (as Assignr names them)',
    evVenuesHint: 'Picked from games Assignr sent in the last and next 60 days. Only an exact match works, so only exact names are offered.',
    evVenueSearch: 'Filter venues',
    evPrefix: 'Game number prefix',
    evPrefixHint: 'Seen in the game numbers at these venues around the start date. Pick one so this event never shares a board with another at the same venue.',
    evLeagueName: 'League, as Assignr names it',
    evSite: 'Assignr site',
    evTools: 'Tools on for this event',
    evAlerts: 'Alert emails (comma separated)',
    evBlurb: 'One line referees see about this event',
    evActive: 'Active',
    evCheck: 'Check',
    evCheckResult: 'On the start date, these venues have {g} games, {p} with the prefix.',
    evCheckNone: 'No games found for these venues on the start date. Check the venue names and the date before saving.',
    evSave: 'SAVE EVENT',
    evSaving: 'Saving...',
    evSaved: 'Saved. The board and the Hub use it now.',
    evMissing: 'Still needed:',
    evOn: 'on',
    evOff: 'off',
    tools: { hub: 'Hub', coaching: 'Coaching', checkin: 'Check-in', scoreboard: 'Scoreboard', scoreentry: 'Score entry', rules: 'Rules', screports: 'End of day reports', incident: 'Incident reports' },
    staffCheckin: 'Check in',
    go: 'Go',
    noMatchShort: 'No match',
    allVenuesPick: 'All venues',
    refereeHQ: 'Referee HQ',
    siteStaff: 'Site staff',
    findRefHere: 'Find a referee at this venue',
    fieldOne: 'field',
    fieldMany: 'fields',
    state_upcoming: 'UPCOMING',
    state_live: 'ON NOW',
    state_done: 'DONE',
    notIn: 'not checked in',
    evaluatorOpen: 'Formal evaluation (Evaluator)',
    evaluatorHint: 'Live capture for upgrade, maintenance or development. Prefilled from this game.',
    library: 'Library',
    eodEntry: 'End of day',
    eodEntryHint: 'Your hours and notes for the day, for pay',
    eodTitle: 'END OF DAY',
    eodLead: 'Your hours and a few words on the day. This is what you are paid from, so file it before you leave the venue.',
    eodRole: 'Your role today',
    roles: { sc: 'Site Coordinator', sm: 'Site Mentor', coach: 'Referee Coach', mentor: 'Referee Mentor', other: 'Other' },
    eodVenue: 'Venue',
    eodIn: 'Time in',
    eodOut: 'Time out',
    eodGames: 'Games covered',
    eodIncidents: 'Incidents',
    eodNotes: 'Notes on the day',
    eodNotesPlaceholder: 'What went well, what did not, who stood out, anything staff should know.',
    eodFile: 'FILE MY HOURS',
    eodFiling: 'Filing...',
    eodFiled: 'Filed. Thank you for the day.',
    eodHours: 'hours',
    eodMine: 'My reports',
    eodAll: 'Everyone, by day',
    eodNone: 'No reports yet.',
    eodBothTimes: 'Both times, please.',
    gsaOpen: 'Game Scoring Assistant (PlayMetrics)',
    gsaHint: 'Roster, score and misconduct on PlayMetrics, for this game',
    other: 'Other',
    refCardTitle: 'Referee',
    refNoRecord: 'No record found for this name. The name on the game may not be linked to a person yet.',
    refSeason: 'This season',
    refGames: 'games',
    refCenter: 'in the center',
    refFirst: 'first game',
    refLast: 'last game',
    refSeen: 'notes',
    refReleased: 'released',
    refCoaches: 'coaches',
    refEvals: 'evaluations this year',
    refNotes: 'Released notes',
    refNoNotes: 'No released notes this season.',
    staffList: 'Everyone with a title',
    staffTitle: 'STAFF',
    staffLead: 'Everyone holding a title above referee, with every title they hold. Learning Center titles in grey, Colorado titles in green.',
    staffFilter: 'Filter by title',
    alertOpen: 'Open',
    eodCounted: 'Games covered and incidents are counted from the day automatically.',
    rulesNotPosted: 'Rules for this event are not posted yet. We will post them here as soon as the league or tournament sends them.',
    evRules: 'Referee rules for this event',
    evRulesHint: 'A page in the Hub (rules-nat1.html) or any web address. Leave it empty and referees are told the rules are not posted yet. Rules never carry over from another event.',
    linkList: 'Names to link',
    linkTitle: 'NAMES TO LINK',
    linkLead: 'Names on games this season with no person behind them. Until a name is linked, that referee\'s games do not count and they cannot sign in to see their notes. Tap a name, then tap the person it is.',
    linkGames: 'games',
    linkPick: 'Who is this?',
    linkOther: 'Someone else: search below',
    linkDone: 'Linked',
    linkNone: 'Every name on a game this season is linked.',
    linkNoSuggest: 'No close match. Search for the person below and tap them.',
    refLastSeen: 'Last seen',
    refNext: 'Next game',
    refNextHint: 'A coach or mentor could be there.',
    eodReportOne: 'report',
    eodReportMany: 'reports',
    evalReqTitle: 'Formal evaluation',
    evalReqLead: 'Ask the Director of Referee Development to send a coach to this game. For keeping your grade next year, or for an upgrade.',
    evalPurpose: { maintenance: 'Maintenance (keep my grade)', upgrade_regional: 'Upgrade to Regional', upgrade_national: 'Upgrade to National' },
    evalStatus: { requested: 'Requested. Waiting for a coach to be assigned.', assigned: 'A coach is assigned and will be there.', done: 'Done.', declined: 'Not scheduled this time.' },
    evalReqSend: 'ASK FOR AN EVALUATION',
    evalAssignedTitle: 'Formal evaluations assigned to you',
    evalAssignedHint: 'Open the game and tap Formal evaluation to use the Evaluator.',
    tabEvals: 'Evaluations',
    evalsLead: 'Referees asking for a formal evaluation. Assign a coach; the Evaluator opens for them on that game. Only a National Referee Coach can evaluate for National.',
    evalsOpen: 'Requested',
    evalsAssigned: 'Assigned',
    evalCoach: 'Coach:',
    evalAssign: 'Assign a coach',
    evalDecline: 'Not this time',
    evalMarkDone: 'Mark done',
    evalNationalOnly: 'National upgrade: only National Referee Coaches and FIFA Evaluators are listed.',
    signOut: 'Sign out',
    builtWith: 'Built with JAReferee',
    theme: 'Switch between light and dark',
    langSwitch: 'Español'
  },
  es: {
    appName: 'Árbitros de Colorado',
    signinTitle: 'Iniciar sesión',
    signinLead: 'Usa el correo electrónico de tu registro de árbitro.',
    email: 'Tu correo electrónico',
    sendCode: 'Envíame un código',
    sending: 'Enviando tu código...',
    codeSent: 'Revisa tu correo: te enviamos un código de 6 dígitos. Vale por 10 minutos.',
    codeLabel: 'El código que te enviamos',
    signIn: 'Entrar',
    noRecord: 'No encontramos un registro de árbitro con ese correo. Usa el correo de tu cuenta del Learning Center, o pregunta en la carpa de árbitros.',
    tooMany: 'Se enviaron demasiados códigos. Espera unos minutos e inténtalo de nuevo.',
    couldNotSend: 'No se pudo enviar el código: ',
    badCode: 'Ese código no funcionó. Revisa los dígitos e inténtalo de nuevo.',
    wholeCode: 'Escribe el código completo del correo.',
    greeting: { morning: 'Buenos días', afternoon: 'Buenas tardes', evening: 'Buenas noches' },
    minutesToKickoff: 'minutos<br>para el inicio',
    hoursToKickoff: 'horas<br>para el inicio',
    kickedOff: 'inició hace',
    minAgo: 'minutos',
    noGamesToday: 'No tienes partidos hoy.',
    noGamesHint: 'Cuando Assignr publique tu próximo partido, aparecerá aquí. Mientras tanto, la Biblioteca es un buen lugar.',
    nextGame: 'Tu próximo partido',
    youAre: 'Eres',
    role: { cr: 'el árbitro central', ar1: 'el asistente 1', ar2: 'el asistente 2', fourth: 'el cuarto árbitro' },
    checkIn: 'REGISTRARME',
    checkingIn: 'Registrando...',
    checkedIn: 'REGISTRADO',
    checkedInAt: 'El personal ya sabe que llegaste.',
    checkinFailed: 'No se pudo registrar. Guardamos tu toque; inténtalo cuando tengas señal, o regístrate en la carpa de árbitros.',
    checkinWhere: 'Regístrate en la carpa de árbitros al llegar.',
    details: 'Detalles',
    laterToday: 'Más tarde hoy',
    noteFrom: 'después de',
    allNotes: 'Todas tus notas',
    noNotes: 'Aún no hay comentarios. Cuando un coach o mentor vea uno de tus partidos, su nota aparecerá aquí.',
    fromState: 'De Colorado Soccer',
    rules: 'Reglas',
    map: 'Mapa',
    help: 'NECESITO AYUDA',
    yourDay: 'Tu día',
    back: 'Atrás',
    kicksIn: 'Inicia en',
    home: 'Local, de oscuro',
    away: 'Visitante, de claro',
    crew: 'Tu equipo arbitral',
    alone: 'Este partido es solo tuyo; no hay asistentes en este formato.',
    afterGame: 'DESPUÉS DEL PARTIDO',
    reportScore: 'Reportar el marcador',
    reportScoreHint: 'Luego entrega la hoja del partido en la carpa. Los marcadores también van en PlayMetrics, como siempre.',
    incident: 'Presentar un reporte de incidente',
    incidentHint: 'Un reporte escrito, con tus palabras, para una expulsión, un despido o cualquier cosa inusual',
    incidentNote: 'El departamento de árbitros lee los reportes; no alertan a nadie de inmediato. Si algo está pasando ahora mismo, usa NECESITO AYUDA. Las amonestaciones y expulsiones también van en tu reporte de Assignr, como siempre.',
    comingSoon: 'Pronto estará aquí. Por ahora, usa la página actual.',
    helpTitle: '¿QUÉ ESTÁ PASANDO?',
    helpLead: 'Elige una opción. Llega a la carpa de árbitros con tu nombre y tu cancha. No se envía nada hasta que confirmes.',
    reasons: {
      roster: 'Problema con la lista o la hoja del partido',
      spectator: 'Problema con un entrenador o espectador',
      redcard: 'Tarjeta roja o expulsión',
      fight: 'Pelea o amenaza',
      injury: 'Lesión, necesito al entrenador médico'
    },
    hotline: 'Enviar texto a la línea de árbitros',
    groupUrgent: 'Envía un texto ahora mismo al coordinador de sede y al personal de tu sede',
    groupQueue: 'Un mensaje a la carpa de árbitros',
    groupHotline: 'Sin personal donde estás, u otra cosa',
    hotlineDesktop: 'Escribe a la línea de árbitros desde tu teléfono:',
    hotlineNote: 'Un Referee Coach vigila la línea todo el día, todos los días. Úsala cuando no haya coordinador de sede donde estás, o para cualquier cosa que no esté en esta lista.',
    youPicked: 'Elegiste',
    goesTo: 'Envía un texto al coordinador de sede y a todos los que puedan responder en tu sede ahora mismo.',
    goesToQueue: 'Llega a la carpa de árbitros como mensaje.',
    sendIt: 'ENVIAR',
    neverMind: 'Olvídalo',
    sendingHelp: 'Enviando...',
    helpSent: 'Enviado. La carpa de árbitros ya lo tiene.',
    helpSentAt: 'Enviado a las',
    helpFailed: 'No se pudo enviar. Escribe a la línea de árbitros:',
    helpFoot: 'Si la sede no tiene personal conectado, todo esto va a la línea de árbitros.',
    coachingEntry: 'Coaching',
    coachingEntryHint: 'Observa un partido y deja una nota',
    coachingTitle: 'COACHING',
    coachingLead: 'Elige dónde estás. Se listan todos los partidos de ahí; toca uno para escribir una nota sobre un árbitro.',
    noVenuesToday: 'No hay partidos en ningún lugar hoy.',
    venue: 'Sede',
    myNotes: 'Mis notas',
    myNotesLead: 'Lo que escribiste, y en qué se convirtió tras la limpieza. Siempre ves ambos.',
    noMyNotes: 'Aún no has escrito una nota.',
    crewPick: '¿A quién observaste?',
    noteLabel: 'Tu nota',
    notePlaceholder: 'Lo que viste, lo que estuvo bien, una cosa para trabajar. Escríbelo como lo dirías.',
    areaLabel: '¿A qué área se refiere? (opcional)',
    areas: { laws: 'Reglas', reading: 'Lectura del juego', fitness: 'Condición física', presence: 'Cómo te presentas' },
    saveNote: 'GUARDAR NOTA',
    savingNote: 'Guardando...',
    noteSaved: 'Guardada y firmada',
    noteSavedHint: 'Ahora pasa a limpieza y luego al Director de Desarrollo de Árbitros. Puedes verla cuando quieras en Mis notas.',
    noteFailed: 'No se pudo guardar. Tus palabras siguen aquí; toca de nuevo cuando tengas señal.',
    another: 'Anotar a otro árbitro de este partido',
    rawLabel: 'Lo que escribiste',
    cleanLabel: 'Tras la limpieza',
    notCleaned: 'Aún sin limpiar',
    status: { pending: 'Esperando limpieza', cleaned: 'Limpia, esperando aprobación', approved: 'Aprobada, enviada al árbitro', edited: 'Aprobada, enviada al árbitro', rejected: 'No enviada' },
    signedAs: 'Firmada como',
    reviewEntry: 'Revisión de comentarios',
    reviewEntryHint: 'Limpia, aprueba y entrega comentarios a los árbitros',
    reviewTitle: 'REVISIÓN',
    reviewLead: 'Cada nota que escribió un coach, original junto a limpia. Limpia las pendientes, lee ambas, aprueba las listas. Las aprobadas llegan al árbitro en su Hub de inmediato.',
    filterPending: 'En espera',
    filterCleaned: 'Limpias',
    filterApproved: 'Aprobadas',
    loadingReview: 'Cargando notas...',
    nothingHere: 'Nada por aquí.',
    cleanBtn: 'Limpiar esta nota',
    cleanAll: 'Limpiar todas las pendientes',
    cleaning: 'Limpiando...',
    approveBtn: 'APROBAR Y ENTREGAR',
    approveAll: 'Aprobar y entregar todas las limpias',
    approving: 'Aprobando...',
    approved: 'Aprobada',
    approvedBy: 'por',
    flaggedNote: 'Marcada por la limpieza: léela antes de aprobar',
    reviewFailed: 'No se pudo. Inténtalo de nuevo.',
    notAllowed: 'Tus títulos no abren Revisión.',
    count: { one: '1 nota', many: '{n} notas' },
    notSeen: 'Sin observar aún',
    notSeenLong: 'Nadie le ha dejado una nota a este árbitro todavía. La tuya sería la primera.',
    seenTimes: 'Observado {n} veces, la última',
    alreadySaid: 'Ya se dijo sobre este árbitro ({n} notas entregadas). Añade, no repitas.',
    redMeans: 'Un nombre en rojo no ha recibido comentarios aún. Esos van primero.',
    aiLabel: 'Tras la limpieza',
    releasedLabel: 'Entregada al árbitro',
    notReleased: 'Aún no entregada',
    readBy: 'Leída por el árbitro el',
    centerEntry: 'Desarrollo arbitral',
    centerEntryHint: 'Cobertura, coaches, programación y el coach de IA para coaches',
    centerTitle: 'DESARROLLO ARBITRAL',
    centerLead: 'Quién ha sido observado, quién no, qué hacen los coaches y ayuda para los propios coaches.',
    tabCoverage: 'Cobertura',
    tabCoaches: 'Coaches',
    tabAi: 'Coach de IA',
    tabQueue: 'Cola',
    stWorked: 'árbitros activos esta temporada',
    stSeen: 'observados al menos una vez',
    stNever: 'nunca observados',
    stRead: 'notas entregadas leídas',
    neverSeenTitle: 'Nunca observados, más partidos primero',
    seenOnce: 'Observados una vez',
    gamesWorked: 'partidos',
    lastGame: 'último partido',
    coachesTitle: 'Coaches y mentores, últimos 30 días',
    coachNotes: 'notas',
    coachRefs: 'árbitros',
    coachReleased: 'entregadas',
    coachRead: 'leídas',
    noCoachActivity: 'Sin notas en los últimos 30 días.',
    aiLead: 'Lee cada nota que escribió un coach en un rango de fechas y redacta un mensaje corto y amable para cada coach: qué funcionó, qué ajustar, cómo dar más al árbitro en menos palabras. No se envía nada hasta que toques Enviar.',
    aiFrom: 'Desde',
    aiTo: 'Hasta',
    aiRun: 'REDACTAR NOTAS PARA COACHES',
    aiRunning: 'Leyendo las notas y redactando...',
    aiNone: 'No hay notas en ese rango.',
    aiSend: 'Enviar a',
    aiSending: 'Enviando...',
    aiSent: 'Enviado',
    aiNoEmail: 'Este coach no tiene correo registrado',
    aiFailed: 'No se pudo.',
    queueWaiting: 'esperando limpieza',
    queueCleaned: 'limpias, listas para entregar',
    openReview: 'Abrir Revisión',
    opsEntry: 'Centro de mando',
    opsEntryHint: 'Cada sede, equipo arbitral y registro, en vivo. Cambios, ayuda, protección, avisos',
    opsTitle: 'CENTRO DE MANDO',
    opsLead: 'Cada sede con partidos ese día. Verde es registrado. Rojo es una llamada de ayuda abierta.',
    tabBoard: 'Sedes',
    tabRetain: 'Retener',
    tabBulletins: 'Avisos',
    stVenues: 'sedes',
    stGames: 'partidos',
    stCheckedIn: 'registrados',
    stHelpOpen: 'ayuda abierta',
    noGamesDay: 'No hay partidos ese día.',
    allVenues: 'Todas las sedes',
    helpOpenAt: 'Ayuda abierta',
    ackInOld: 'Por ahora, atiende las llamadas de ayuda en el centro de mando actual.',
    retainLead: 'Árbitros que trabajan pero nadie ha observado, y árbitros que han dejado de aparecer.',
    retainNever: 'Trabajando, nunca observados (3+ partidos)',
    retainQuiet: 'Sin partidos en 30 días',
    noneHere: 'Nadie aquí. Bien.',
    bulletinsLead: 'Lo que cada árbitro ve en Tu día. Los vigentes están dentro de su rango de fechas.',
    bulletinLive: 'Vigente',
    bulletinOver: 'Terminado',
    bulletinFuture: 'Programado',
    newBulletin: 'Nuevo aviso',
    bulTitle: 'Título',
    bulBody: 'Mensaje',
    bulFrom: 'Desde',
    bulTo: 'Hasta',
    bulPost: 'PUBLICAR',
    bulPosting: 'Publicando...',
    bulPosted: 'Publicado. Los árbitros ya lo ven.',
    bulClear: 'Retirar',
    bulCleared: 'Retirado',
    ackEnroute: 'Voy en camino',
    ackHandled: 'Resuelto',
    change: 'Cambiar',
    fieldLabel: 'Cancha',
    saveChanges: 'GUARDAR CAMBIOS',
    saving: 'Guardando...',
    peopleEntry: 'Personas',
    peopleEntryHint: 'Busca a cualquiera, da o quita un título de Colorado',
    peopleTitle: 'PERSONAS',
    peopleLead: 'Escribe un nombre. Los títulos del Learning Center llegan solos y no se cambian aquí. Los títulos de Colorado los das tú.',
    peopleSearch: 'Buscar por nombre',
    noMatch: 'Nadie con ese nombre.',
    lcTitles: 'Del Learning Center',
    coTitles: 'Títulos de Colorado',
    addTitle: 'Añadir un título',
    remove: 'Quitar',
    greenBadge: 'Insignia verde (menor de 18)',
    titleGiven: 'Añadido',
    titleTaken: 'Quitado',
    noneYet: 'Ninguno aún',
    tabProtection: 'Protección',
    protectionLead: 'Asignaciones en las próximas dos semanas donde la categoría de edad está por encima de la edad del árbitro. Un aviso para ti y para el asignador. No es una marca contra el árbitro.',
    alertRefresh: 'Revisar asignaciones ahora',
    alertsOpen: 'Abiertas',
    alertsHandled: 'Atendidas',
    alertAgeMsg: '{group} está por encima de la edad de este árbitro ({age}).',
    adult: 'Adultos',
    alertSeenBtn: 'Visto, asignador avisado',
    alertDismissBtn: 'Está bien así',
    alertSeen: 'Visto',
    alertDismissed: 'Está bien así',
    alertOnGame: 'Aviso de categoría de edad para {n} de este equipo arbitral',
    tabSchedule: 'Programación',
    scheduleLead: 'Elige el día y el bloque, luego una sede, luego las canchas, luego el coach. Un bloque significa: hablar cara a cara con cada árbitro de esas canchas, y luego recorrer la sede.',
    blockAm: 'Mañana',
    blockPm: 'Tarde',
    blockAll: 'Todo el día',
    availableCount: '{n} coaches dijeron que están libres en este bloque.',
    availableMeans: 'Una marca significa que el coach dijo que está libre en este bloque. Aun así puedes elegir a cualquiera.',
    pickFields: 'Canchas (sin elegir ninguna, es toda la sede)',
    wholeVenue: 'toda la sede',
    addCoach: 'Añadir un coach o mentor',
    coachSearch: 'Escribe un nombre',
    yourBlock: 'Tu bloque de hoy',
    blockJob: 'Habla cara a cara con cada árbitro de estas canchas, y luego recorre la sede y anota a quien sea.',
    debriefed: 'Anotados hasta ahora: {d} de {n} árbitros en tus canchas.',
    whenFree: '¿Cuándo puedes venir a observar? Toca lo que puedas.',
    yours: 'tuyo',
    goldMeans: 'Los partidos con borde dorado están en tus canchas en tu bloque.',
    coachHereToday: 'Hoy hay un coach o mentor en tu sede. Salúdalo.',
    lanyard: 'Busca el cordón y el gafete de CSA.',
    badgeCaption: 'Gafete negro con cordón, con el nombre y el título del coach.',
    scoreSent: 'Marcador enviado',
    scoreFix: '¿Está mal? Cámbialo abajo.',
    scoreChange: 'Cambiar el marcador',
    scoreLater: 'Reporta el marcador aquí después del silbatazo final.',
    scoreSend: 'ENVIAR EL MARCADOR',
    sending: 'Enviando...',
    scoreBoth: 'Los dos marcadores, por favor.',
    scoreFailed: 'No se pudo enviar el marcador. Inténtalo de nuevo o avisa en la carpa.',
    previewing: 'Viendo como {name}.',
    previewNoWrite: 'Solo ver; nada de lo que toques se envía.',
    previewStop: 'Dejar de ver como',
    viewAs: 'Ver como (ADMIN)',
    viewAsHint: 'Ve la app exactamente como la ve otra persona. Nada de lo que hagas mientras ves se guarda.',
    setupEntry: 'Configuración',
    setupEntryHint: 'Eventos y herramientas, sin tocar la hoja',
    setupTitle: 'EVENTOS',
    setupLead: 'Un torneo o una liga, qué activa y dónde están sus partidos. No se guarda nada hasta que esté completo.',
    newEvent: 'Nuevo evento',
    evName: 'Nombre',
    evId: 'Id corto (letras y guiones; será la dirección)',
    evType: 'Tipo',
    evTournament: 'Torneo',
    evLeague: 'Liga',
    evDates: 'Fechas',
    evVenues: 'Sedes (como las nombra Assignr)',
    evVenuesHint: 'Tomadas de los partidos que Assignr envió en los últimos y próximos 60 días. Solo funciona la coincidencia exacta, así que solo se ofrecen nombres exactos.',
    evVenueSearch: 'Filtrar sedes',
    evPrefix: 'Prefijo del número de partido',
    evPrefixHint: 'Visto en los números de partido de estas sedes cerca de la fecha de inicio. Elige uno para que este evento nunca comparta tablero con otro en la misma sede.',
    evLeagueName: 'Liga, como la nombra Assignr',
    evSite: 'Sitio de Assignr',
    evTools: 'Herramientas activas para este evento',
    evAlerts: 'Correos de alerta (separados por comas)',
    evBlurb: 'Una línea que los árbitros ven sobre este evento',
    evActive: 'Activo',
    evCheck: 'Verificar',
    evCheckResult: 'En la fecha de inicio, estas sedes tienen {g} partidos, {p} con el prefijo.',
    evCheckNone: 'No se encontraron partidos para estas sedes en la fecha de inicio. Revisa los nombres de las sedes y la fecha antes de guardar.',
    evSave: 'GUARDAR EVENTO',
    evSaving: 'Guardando...',
    evSaved: 'Guardado. El tablero y el Hub ya lo usan.',
    evMissing: 'Aún falta:',
    evOn: 'activo',
    evOff: 'inactivo',
    tools: { hub: 'Hub', coaching: 'Coaching', checkin: 'Registro', scoreboard: 'Marcador', scoreentry: 'Captura de marcador', rules: 'Reglas', screports: 'Reportes de fin de día', incident: 'Reportes de incidente' },
    staffCheckin: 'Registrar',
    go: 'Ir',
    noMatchShort: 'Sin resultados',
    allVenuesPick: 'Todas las sedes',
    refereeHQ: 'Carpa de árbitros',
    siteStaff: 'Personal de sede',
    findRefHere: 'Buscar un árbitro en esta sede',
    fieldOne: 'cancha',
    fieldMany: 'canchas',
    state_upcoming: 'PRÓXIMO',
    state_live: 'EN JUEGO',
    state_done: 'TERMINADO',
    notIn: 'sin registrar',
    evaluatorOpen: 'Evaluación formal (Evaluator)',
    evaluatorHint: 'Captura en vivo para ascenso, mantenimiento o desarrollo. Prellenada con este partido.',
    library: 'Biblioteca',
    eodEntry: 'Fin del día',
    eodEntryHint: 'Tus horas y notas del día, para el pago',
    eodTitle: 'FIN DEL DÍA',
    eodLead: 'Tus horas y unas palabras sobre el día. De aquí sale tu pago, así que preséntalo antes de irte de la sede.',
    eodRole: 'Tu rol de hoy',
    roles: { sc: 'Coordinador de sede', sm: 'Mentor de sede', coach: 'Referee Coach', mentor: 'Referee Mentor', other: 'Otro' },
    eodVenue: 'Sede',
    eodIn: 'Hora de entrada',
    eodOut: 'Hora de salida',
    eodGames: 'Partidos cubiertos',
    eodIncidents: 'Incidentes',
    eodNotes: 'Notas del día',
    eodNotesPlaceholder: 'Qué salió bien, qué no, quién destacó, algo que el personal deba saber.',
    eodFile: 'PRESENTAR MIS HORAS',
    eodFiling: 'Presentando...',
    eodFiled: 'Presentado. Gracias por el día.',
    eodHours: 'horas',
    eodMine: 'Mis reportes',
    eodAll: 'Todos, por día',
    eodNone: 'Aún no hay reportes.',
    eodBothTimes: 'Las dos horas, por favor.',
    gsaOpen: 'Asistente de marcador (PlayMetrics)',
    gsaHint: 'Lista, marcador y conducta en PlayMetrics, para este partido',
    other: 'Otro',
    refCardTitle: 'Árbitro',
    refNoRecord: 'No hay registro para este nombre. Puede que el nombre del partido aún no esté vinculado a una persona.',
    refSeason: 'Esta temporada',
    refGames: 'partidos',
    refCenter: 'en el centro',
    refFirst: 'primer partido',
    refLast: 'último partido',
    refSeen: 'notas',
    refReleased: 'entregadas',
    refCoaches: 'coaches',
    refEvals: 'evaluaciones este año',
    refNotes: 'Notas entregadas',
    refNoNotes: 'Sin notas entregadas esta temporada.',
    staffList: 'Todos con un título',
    staffTitle: 'PERSONAL',
    staffLead: 'Todos los que tienen un título por encima de árbitro, con cada título que tienen. Los del Learning Center en gris, los de Colorado en verde.',
    staffFilter: 'Filtrar por título',
    alertOpen: 'Abierta',
    eodCounted: 'Los partidos cubiertos y los incidentes se cuentan del día automáticamente.',
    rulesNotPosted: 'Las reglas de este evento aún no están publicadas. Las publicaremos aquí en cuanto la liga o el torneo las envíe.',
    evRules: 'Reglas para árbitros de este evento',
    evRulesHint: 'Una página del Hub (rules-nat1.html) o cualquier dirección web. Si se deja vacío, a los árbitros se les dice que las reglas aún no están publicadas. Las reglas nunca pasan de un evento a otro.',
    linkList: 'Nombres por vincular',
    linkTitle: 'NOMBRES POR VINCULAR',
    linkLead: 'Nombres en partidos de esta temporada sin una persona detrás. Hasta que un nombre esté vinculado, los partidos de ese árbitro no cuentan y no puede iniciar sesión para ver sus notas. Toca un nombre y luego a la persona que es.',
    linkGames: 'partidos',
    linkPick: '¿Quién es?',
    linkOther: 'Otra persona: busca abajo',
    linkDone: 'Vinculado',
    linkNone: 'Cada nombre en un partido de esta temporada está vinculado.',
    linkNoSuggest: 'Sin coincidencia cercana. Busca a la persona abajo y tócala.',
    refLastSeen: 'Visto por última vez',
    refNext: 'Próximo partido',
    refNextHint: 'Un coach o mentor podría estar ahí.',
    eodReportOne: 'reporte',
    eodReportMany: 'reportes',
    evalReqTitle: 'Evaluación formal',
    evalReqLead: 'Pide al Director de Desarrollo de Árbitros que envíe un coach a este partido. Para mantener tu grado el próximo año, o para un ascenso.',
    evalPurpose: { maintenance: 'Mantenimiento (conservar mi grado)', upgrade_regional: 'Ascenso a Regional', upgrade_national: 'Ascenso a Nacional' },
    evalStatus: { requested: 'Solicitada. Esperando que se asigne un coach.', assigned: 'Un coach está asignado y estará ahí.', done: 'Hecha.', declined: 'No programada esta vez.' },
    evalReqSend: 'PEDIR UNA EVALUACIÓN',
    evalAssignedTitle: 'Evaluaciones formales asignadas a ti',
    evalAssignedHint: 'Abre el partido y toca Evaluación formal para usar el Evaluator.',
    tabEvals: 'Evaluaciones',
    evalsLead: 'Árbitros que piden una evaluación formal. Asigna un coach; el Evaluator se abre para ellos en ese partido. Solo un National Referee Coach puede evaluar para Nacional.',
    evalsOpen: 'Solicitadas',
    evalsAssigned: 'Asignadas',
    evalCoach: 'Coach:',
    evalAssign: 'Asignar un coach',
    evalDecline: 'Esta vez no',
    evalMarkDone: 'Marcar hecha',
    evalNationalOnly: 'Ascenso a Nacional: solo se listan National Referee Coaches y FIFA Evaluators.',
    signOut: 'Cerrar sesión',
    builtWith: 'Hecho con JAReferee',
    theme: 'Cambiar entre claro y oscuro',
    langSwitch: 'English'
  }
};
